### PR TITLE
added thread safety to holidays dictionary creation and population

### PR DESCRIPTION
**Pull request by alnimin**

### CODE REVIEW

**Comment by johnkors** [comment]
@follesoe / @judoole ? I don't have owner access to this repo at BEKK Open any longer.

**Comment by johnkors** [comment]
Anyone alive to respond to this, or do you want me to take responsibility for this repo..?

**Comment by lillesand** [comment]
Hey ho @johnkors! I Think the best thing to do is to transfer ownership to you. I'll be in touch directly so we can hash out the details.

**Comment by johnkors** [comment]
We got it figured out via other channels, @lillesand  :)

**Comment by johnkors** [comment]
thx, @alnimin :)

**Comment by lillesand** [comment]
Ah, I'm one step behind 😀 . Excellent – you can safely ignore my chat messages in several other channels 😉

**Comment by johnkors** [comment]
Deployed to nuget as v.0.2.0, @alnimin 

https://www.nuget.org/packages/NoCommons/

**Comment by alnimin** [comment]
Great, thanks! :+1:

**Pull request merged**
